[program:atmos-hls]
command=python3 -u /var/azuracast/www/util/atmos-hls/worker.py
user=azuracast
priority=700
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/var/azuracast/www_tmp/service_atmos_hls.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
redirect_stderr=true
